[package]
name = "advent_of_code_2016"
version = "0.1.0"
authors = ["Christopher Luu <nuudles@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
